apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: iris-classification
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: iris-classification
  template:
    metadata:
      labels:
        app: iris-classification
    spec:
      containers:
      - image: ksr1729/iris_classification:latest
        name: iris-classification
        ports:
        - containerPort: 80
