apiVersion: v1
kind: Service
metadata:
  name: iris-classification
spec:
  type: NodePort
  ports:
  - port: 5000
    targetPort: 5000
  selector:
    app: iris-classification
    env: prod
