apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: iris-classification
spec:
  replicas: 2
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: iris-classification
      env: prod
  template:
    metadata:
      labels:
        app: iris-classification
        env: prod
    spec:
      containers:
      - image: ksr1729/iris_classification:e616307
        name: iris-classification
        ports:
        - containerPort: 80
